# Generated by Django 5.2.7 on 2026-08-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='guest_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
