# Generated by Django 5.2.7 on 2026-08-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rsvp_guest_count_rsvp_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
