# Generated by Django 5.2.7 on 2026-08-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_channel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
